# Read the documentation: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/Resources/doc/index.md#step-5-configure-fosoauthserverbundle
fos_oauth_server:
    db_driver: orm

    client_class: App\Acme\ApiBundle\Entity\Client
    access_token_class: App\Acme\ApiBundle\Entity\AccessToken
    refresh_token_class: App\Acme\ApiBundle\Entity\RefreshToken
    auth_code_class: App\Acme\ApiBundle\Entity\AuthCode

    service:
        user_provider: fos_user.user_provider.username
        options:
            token_type: Bearer
