nelmio_api_doc:
    documentation:
        info:
            title: Smart Cafe
            version: 1.0.0
        securityDefinitions:
            password:
                type: oauth2
                description: provides a password flow access_token
                flow: password
                tokenUrl: /index.php/oauth/v2/token
                name: Authorization
            client_credentials:
                type: oauth2
                description: provides a client_credentials flow access_token
                flow: application
                tokenUrl: /index.php/oauth/v2/token
                name: Authorization
        security:
            - password: []
            - client_credentials: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
